using System.IO;
using System.IO.Compression;
using System.Reflection;
using System.Text.Json;
using PathFinder.Models;

namespace PathFinder.Services;

/// <summary>
/// Loads and caches the EDIFACT directory definitions bundled in the assembly
/// as an embedded resource (<c>EdifactDefinitions.json.gz</c>).
/// All members are thread-safe after the first call.
/// </summary>
internal static class EdifactDefinitionService
{
    private static EdifactAllDefinitions? _definitions;
    private static readonly object _lock = new();

    private const string ResourceName =
        "PathFinder.Resources.EdifactDefinitions.json.gz";

    // ── Public API ────────────────────────────────────────────────────────────

    /// <summary>
    /// Returns the message definition for the given directory code and message
    /// type, or <c>null</c> if not found.
    /// </summary>
    internal static EdifactMessageDef? LookupMessage(string directory, string messageType)
    {
        var defs = Definitions;
        if (!defs.Directories.TryGetValue(directory.ToUpperInvariant(), out var dir))
            return null;
        dir.Messages.TryGetValue(messageType.ToUpperInvariant(), out var msg);
        return msg;
    }

    /// <summary>
    /// Returns the segment field definition for the given tag, checking first
    /// in the specified directory and then in the ISO9735 service segments.
    /// Returns <c>null</c> when no definition is found.
    /// </summary>
    internal static EdifactSegmentDef? LookupSegment(string directory, string tag)
    {
        var defs = Definitions;
        var ucTag = tag.ToUpperInvariant();

        if (defs.Directories.TryGetValue(directory.ToUpperInvariant(), out var dir)
            && dir.Segments.TryGetValue(ucTag, out var seg))
            return seg;

        if (defs.ServiceSegments.TryGetValue(ucTag, out var svcSeg))
            return svcSeg;

        return null;
    }

    /// <summary>
    /// Returns the allowed code values (code → description) for the given data
    /// element ID within a directory, or an empty dictionary when no code list is found.
    /// </summary>
    internal static IReadOnlyDictionary<string, string> LookupCodeList(string directory, string elementId)
    {
        var defs = Definitions;
        if (!defs.Directories.TryGetValue(directory.ToUpperInvariant(), out var dir))
            return new Dictionary<string, string>();
        return dir.CodeLists.TryGetValue(elementId, out var codes)
            ? codes
            : new Dictionary<string, string>();
    }

    /// <summary>
    /// Returns true when definitions are available for the given directory code.
    /// </summary>
    internal static bool DirectoryKnown(string directory)
        => Definitions.Directories.ContainsKey(directory.ToUpperInvariant());

    // ── Lazy initialization ───────────────────────────────────────────────────

    private static EdifactAllDefinitions Definitions
    {
        get
        {
            if (_definitions is not null)
                return _definitions;

            lock (_lock)
            {
                if (_definitions is not null)
                    return _definitions;

                _definitions = Load();
            }
            return _definitions;
        }
    }

    private static EdifactAllDefinitions Load()
    {
        var asm = Assembly.GetExecutingAssembly();
        using var stream = asm.GetManifestResourceStream(ResourceName);

        if (stream is null)
        {
            // Definitions file not embedded (e.g. not yet generated by the scraper).
            // Return an empty object so the app still starts; validation will report
            // "directory not found" errors instead of crashing.
            return new EdifactAllDefinitions();
        }

        using var gz = new GZipStream(stream, CompressionMode.Decompress);
        using var mem = new MemoryStream();
        gz.CopyTo(mem);
        mem.Position = 0;

        var opts = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
        };

        return JsonSerializer.Deserialize<EdifactAllDefinitions>(mem, opts)
            ?? new EdifactAllDefinitions();
    }
}
